//用户模块
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REPLACE_USERINFO = 'REPLACE_USERINFO';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const SUCCESS_BINDINGPHONE = 'SUCCESS_BINDINGPHONE';
export const PHONE_COUNT_DOWN = 'PHONE_COUNT_DOWN';
export const Email_COUNT_DOWN = 'Email_COUNT_DOWN';
export const START_BTN_CLICK = 'START_BTN_CLICK';
export const END_BTN_CLICK = 'END_BTN_CLICK';
export const SUCCESS_GET_INVITED_CODE_COUNT = 'SUCCESS_GET_INVITED_CODE_COUNT';
//租户模块
export const SUCCESS_GET_TENANT_LIST = 'SUCCESS_GET_TENANT_LIST';
export const SET_TENANTNAME = 'SET_TENANTNAME';
export const GET_USER_LIST_BY_TENANTID = 'GET_USER_LIST_BY_TENANTID';
export const SWITCH_TENANT = 'SWITCH_TENANT';
export const SUCCESS_DEL_USER = 'SUCCESS_DEL_USER';
export const SUCCESS_APPLICATION_LIST = 'SUCCESS_APPLICATION_LIST';
export const PROCESSING_APPLICATION = 'PROCESSING_APPLICATION';
export const SUCCESS_EXIT_TENANT = 'SUCCESS_EXIT_TENANT';
//组织模块
export const SUCCESS_GTE_ORG_LIST = 'SUCCESS_GTE_ORG_LIST';
export const SET_ACTIVE_ORG = 'SET_ACTIVE_ORG';
export const SUCCESS_GET_POST_LIST = 'SUCCESS_GET_POST_LIST';
export const SUCCESS_GET_PERSON_LIST = 'SUCCESS_GET_PERSON_LIST';
export const CHANGE_ACTIVE_ORG = 'CHANGE_ACTIVE_ORG';
export const SUCCESS_GET_ORG_DETAILS = 'SUCCESS_GET_ORG_DETAILS';
export const SUCCESS_GET_POST_DETAILS = 'SUCCESS_GET_POST_DETAILS';
export const SUCCESS_GET_PERSON_DETAILS = 'SUCCESS_GET_PERSON_DETAILS';
export const SUCCESS_GET_USER_NOT_LIKN = 'SUCCESS_GET_USER_NOT_LIKN';
export const CHANGE_USER_LOGINNAME = 'CHANGE_USER_LOGINNAME';
export const CLEAR_HCM_DATA = 'CLEAR_HCM_DATA';

//个人请假模块
export const GTE_CHECKED_LEAVE_TYPE = 'GTE_CHECKED_LEAVE_TYPE';
export const GET_PAGENO = 'GET_PAGENO';
export const SUCCESS_GET_LEAVE_LIST = 'SUCCESS_GET_LEAVE_LIST';
export const SUCCESS_GET_LEAVE_LIST_COUNT = 'SUCCESS_GET_LEAVE_LIST_COUNT';
export const GET_DIALOG_TYPE = 'GET_DIALOG_TYPE';
export const SUCCESS_GET_DIALOG_INFO = 'SUCCESS_GET_DIALOG_INFO';
export const GET_LEAVE_PAGE_TYPE = 'GET_LEAVE_PAGE_TYPE';
export const SET_LEAVE_PORSONNAME = 'SET_LEAVE_PORSONNAME';
export const GET_APPROVER_INFO = 'GET_APPROVER_INFO';
export const GET_TRANSFER_LEAVE_DATA ='GET_TRANSFER_LEAVE_DATA';
export const GET_DIALOG_BASE_INFO='GET_DIALOG_BASE_INFO';
